name: PyLint
on:
  push:
    paths:
      - "**.py"
  workflow_dispatch:
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"

      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black

      - name: Check for showstoppers with autopep8
        run: |
          autopep8 --verbose --in-place --recursive --aggressive .

      - name: Remove unused imports with autoflake
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports .

      - name: Sort imports with isort
        run: |
          isort .

      - name: Format code with black
        run: |
          black --fast .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pylint: auto fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Vivek Kumar
          commit_user_email: VivekKumar-IN@users.noreply.github.com
          commit_author: Vivek Kumar <VivekKumar-IN@users.noreply.github.com>
