name: Recover Previous Files in Dev Branch (with Commit)

on:
  workflow_dispatch: # Manual trigger

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Identify commit SHA
        id: commit_sha
        run: echo "::set-output name=SHA c1a5f23f421ad01eae2a50fcb18bec3d40e4e970"
      - name: Checkout dev branch
        run: git checkout dev
      - name: Checkout specific commit
        run: |
          git checkout ${{ steps.commit_sha.outputs.SHA }}
      - name: Add all changes (stage for commit)
        run: git add .
      - name: Commit changes with message
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Recovered files from commit ${{ steps.commit_sha.outputs.SHA }}"
