name: Recover Previous Files

on:
  workflow_dispatch: # Manual trigger

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Identify commit SHA
        id: commit_sha
        run: echo "::set-output name=SHA c1a5f23f421ad01eae2a50fcb18bec3d40e4e970"
      - name: Checkout specific commit
        run: |
          git checkout ${{ steps.commit_sha.outputs.SHA }}
